"""Generate compiled catalogs for both apps. Run after editing strings.json."""
from pathlib import Path
import json
root=Path(__file__).resolve().parent.parent
d=json.loads((root/'Localization/strings.json').read_text())
def q(s):return json.dumps(s,ensure_ascii=False)
swift='''// Generated by Localization/generate.py. Edit Localization/strings.json instead.
import Foundation

enum AppLanguage {
    static func isChinese(_ language: String) -> Bool {
        let code = language.replacingOccurrences(of: "_", with: "-").lowercased()
        return code == "zh" || code.hasPrefix("zh-")
    }
    static let preferred = Locale.preferredLanguages.first ?? "en"
    static func text(_ key: String, language: String = preferred) -> String {
        isChinese(language) ? key : (english[key] ?? key)
    }
    static let english: [String: String] = [
'''+''.join('        '+q(k)+': '+q(v)+',\n' for k,v in sorted(d.items()))+'''    ]
}
func L(_ key: String) -> String { AppLanguage.text(key) }
func LF(_ key: String, _ arguments: Any...) -> String {
    var text = L(key)
    for (index, value) in arguments.enumerated() {
        text = text.replacingOccurrences(of: "{\\(index)}", with: String(describing: value))
    }
    return text
}
'''
(root/'Sources/Localization.swift').write_text(swift)
cs='''// Generated by Localization/generate.py. Edit Localization/strings.json instead.
using System;
using System.Collections.Generic;
using System.Globalization;
namespace LumaNib;
internal static class L10n
{
    public static bool IsChinese(string language) {
        string code=language.Replace('_','-');
        return code.Equals("zh",StringComparison.OrdinalIgnoreCase) || code.StartsWith("zh-",StringComparison.OrdinalIgnoreCase);
    }
    public static string T(string key) => Text(key,CultureInfo.CurrentUICulture.Name);
    public static string Text(string key,string language) => IsChinese(language) ? key : English.GetValueOrDefault(key,key);
    public static string F(string key,params object[] arguments) => string.Format(CultureInfo.CurrentUICulture,T(key),arguments);
    internal static readonly Dictionary<string,string> English=new() {
'''+''.join('        ['+q(k)+']='+q(v)+',\n' for k,v in sorted(d.items()))+'''    };
}
'''
(root/'Windows/src/Localization.cs').write_text(cs)
print('Generated Swift and C# catalogs:',len(d))
